### ISSUE TITLE
download_song issue

### ISSUE THREAD

**Issue by doglord** [lakshaykalbhor/MusicTools#1]
Hopefully this is helpful and not just something wrong with my computer lol. get_song_url seems to work fine but when I try and use download_song, I get the error 

[0;31mERROR:[0m Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),))

as well as

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>

and also

youtube_dl.utils.ExtractorError: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),))

&

youtube_dl.utils.DownloadError: [0;31mERROR:[0m Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),))

Here's the exact module I was using 

from musictools import musictools

songs_list = musictools.get_song_urls("Tunnel Vision")
print(songs_list[0])

url, title = songs_list[0]
print("TITLE : ", title)
print("URL : ", url)

musictools.download_song(url, title)

**Comment by kalbhor** [comment]
This is an error that occurs in **youtube-dl**. There is a discussion on this issue over [here](https://github.com/rg3/youtube-dl/issues/7309)

**Comment by hundredrab** [comment]
Hey, this issue in youtube-dl has been resolved.
