### ISSUE TITLE
More information on development / contributing

### ISSUE THREAD

**Issue by jwmann** [lakshaykalbhor/MusicTools#3]
I'm thinking about adding a couple features to this library like direct url support and maybe soundcloud support.

Perhaps I'm missing something here, maybe something obvious, not sure.
I followed through with the steps in the README and the setup finished successfully.
How do I test this?

I did `python test/musictools_tests.py` but I get an basic error
````
Traceback (most recent call last):
  File "tests/musictools_tests.py", line 1, in <module>
    from musictools import musictools
  File "/usr/local/lib/python2.7/site-packages/musictools/musictools.py", line 10, in <module>
    from urllib.request import urlopen
ImportError: No module named request
````
Which seems like I'm missing something fundamental in this setup.

Is there some kind of dev environment setup necessary here similar to `npm install`?
I'm developing on OS X 10.11.6 if that helps. Thanks

**Comment by kalbhor** [comment]
In python we use `pip` to install dependencies. Just run `pip install -r requirements.txt` and that should install all the dependencies listed in the `requirements.txt` file.

**Comment by jwmann** [comment]
I figured it was something obvious like this. 
It would good to have a small one liner for contributing on the README for this.

Thanks though!

**Comment by jwmann** [comment]
The tests seems to actually 'run' now but I'm getting this error about Spotify Client ID.
I'm guessing this has something to do with their API and needing an API key or something but as with the above problem, there's not much information about setup.

Is it a Spotify API key? or some kind of other ID? Where does this ID go? where do I get it?
Could you elaborate?

Thanks again

````
Traceback (most recent call last):
  File "tests/musictools_tests.py", line 6, in <module>
    client_id = os.environ["SPOTIFY_CLIENT_ID"]
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SPOTIFY_CLIENT_ID'
````
